POST http://localhost:8080/jrpc
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "method":"add",
  "params":{
    "productCode":"service_smartresident_sr001",
    "priceCode":"sr_base_1y",
    "userId":10429,
    "subscriptionId":16439,
    "data":{
      "testSubscription":true,
      "order":{
        "test":true,
        "comment":"order.test parameter and order object itself is DEPRECATED, use data.testSubscription for determine test status of subscription"
      },
      "parameters":{
        "label":"",
        "firstName":"Иван",
        "lastName":"Фролов",
        "Phone":"79152936861",
        "Email":"ivan.frolov@mts.ru",
        "periodType":"YEARLY",
        "periodLength":1
      },
      "user":{
        "email":"ivan.frolov@mts.ru",
        "phone":"79152936861",
        "phone_comment":"DEPRECATED: phone property is deprecated, use loginPhone or contactPhone or configure productSaleParameters",
        "loginPhone":"79152936861",
        "contactPhone":"79152936861",
        "chargePhone":"79160877247",
        "autoRenewal":true,
        "firstName":"Иван",
        "lastName":"Фролов"
      },
      "company":{
        "comment":"NOTICE: there are user profile parameters, for more flexibility configure productSaleParameters",
        "name":"ПАО МТС",
        "inn":""
      },
      "geo":{
        "country":{
          "name":"Россия"
        },
        "region":{
          "name":"Москва"
        }
      }
    }
  },
  "id":"249151a8-e5d7-0ab4-47a0-52ebd526621e"
}

###



//
//{
//"jsonrpc": "2.0",
//"result": {
//"status": "active",
//"data": {
//"userShownParams": [
//{ "name": "IP", "description": "IP-адрес сервера", "type": "ip", "value": "..."},
//{ "name": "Password", "description": "Пароль администратора сервера", "type":
//"password", "value": "..."},
//{ "name": "Login", "description": "Логин администратора сервера", "type": "stri
//ng", "value": "..."}
//]
//}
//}
//"id": "<requestId>"
//}